language: go

sudo: false
dist: trusty

branches:
  only:
  - master

go:
- 1.11.x

addons:
  postgresql: "11"
  apt:
    packages:
    - postgresql-11
    - postgresql-client-11

before_install:
- sudo /etc/init.d/postgresql stop
- make deps-ci

before_script:
  - psql -c 'create database volusnap_test;' -U postgres
  - cp config_ci.yml config_test.yml

script:
- make test-ci