language: go

sudo: false
dist: trusty

branches:
  only:
  - master

go:
- 1.11.x

addons:
  postgresql: "9.6"

before_install:
- make deps-ci

before_script:
  - psql -c 'create database volusnap_test;' -U postgres
  - cp config_ci.yml config_test.yml
  - cp sql-migrate_ci.yml sql-migrate.yml
  - make migrate-test-up

script:
- make test-ci