// Code generated by SQLBoiler (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	Accounts  string
	SnapRules string
	Snapshots string
	Users     string
}{
	Accounts:  "accounts",
	SnapRules: "snap_rules",
	Snapshots: "snapshots",
	Users:     "users",
}
