// Code generated by SQLBoiler (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/pkg/errors"
	"github.com/volatiletech/null"
	"github.com/volatiletech/sqlboiler/boil"
	"github.com/volatiletech/sqlboiler/queries"
	"github.com/volatiletech/sqlboiler/queries/qm"
	"github.com/volatiletech/sqlboiler/queries/qmhelper"
	"github.com/volatiletech/sqlboiler/strmangle"
)

// Snapshot is an object representing the database table.
type Snapshot struct {
	ID         int       `boil:"id" json:"id" toml:"id" yaml:"id"`
	CreatedAt  null.Time `boil:"created_at" json:"created_at,omitempty" toml:"created_at" yaml:"created_at,omitempty"`
	UpdatedAt  null.Time `boil:"updated_at" json:"updated_at,omitempty" toml:"updated_at" yaml:"updated_at,omitempty"`
	SnapRuleID int       `boil:"snap_rule_id" json:"snap_rule_id" toml:"snap_rule_id" yaml:"snap_rule_id"`

	R *snapshotR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L snapshotL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var SnapshotColumns = struct {
	ID         string
	CreatedAt  string
	UpdatedAt  string
	SnapRuleID string
}{
	ID:         "id",
	CreatedAt:  "created_at",
	UpdatedAt:  "updated_at",
	SnapRuleID: "snap_rule_id",
}

// Generated where

var SnapshotWhere = struct {
	ID         whereHelperint
	CreatedAt  whereHelpernull_Time
	UpdatedAt  whereHelpernull_Time
	SnapRuleID whereHelperint
}{
	ID:         whereHelperint{field: `id`},
	CreatedAt:  whereHelpernull_Time{field: `created_at`},
	UpdatedAt:  whereHelpernull_Time{field: `updated_at`},
	SnapRuleID: whereHelperint{field: `snap_rule_id`},
}

// SnapshotRels is where relationship names are stored.
var SnapshotRels = struct {
	SnapRule string
}{
	SnapRule: "SnapRule",
}

// snapshotR is where relationships are stored.
type snapshotR struct {
	SnapRule *SnapRule
}

// NewStruct creates a new relationship struct
func (*snapshotR) NewStruct() *snapshotR {
	return &snapshotR{}
}

// snapshotL is where Load methods for each relationship are stored.
type snapshotL struct{}

var (
	snapshotColumns               = []string{"id", "created_at", "updated_at", "snap_rule_id"}
	snapshotColumnsWithoutDefault = []string{"created_at", "updated_at", "snap_rule_id"}
	snapshotColumnsWithDefault    = []string{"id"}
	snapshotPrimaryKeyColumns     = []string{"id"}
)

type (
	// SnapshotSlice is an alias for a slice of pointers to Snapshot.
	// This should generally be used opposed to []Snapshot.
	SnapshotSlice []*Snapshot
	// SnapshotHook is the signature for custom Snapshot hook methods
	SnapshotHook func(boil.Executor, *Snapshot) error

	snapshotQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	snapshotType                 = reflect.TypeOf(&Snapshot{})
	snapshotMapping              = queries.MakeStructMapping(snapshotType)
	snapshotPrimaryKeyMapping, _ = queries.BindMapping(snapshotType, snapshotMapping, snapshotPrimaryKeyColumns)
	snapshotInsertCacheMut       sync.RWMutex
	snapshotInsertCache          = make(map[string]insertCache)
	snapshotUpdateCacheMut       sync.RWMutex
	snapshotUpdateCache          = make(map[string]updateCache)
	snapshotUpsertCacheMut       sync.RWMutex
	snapshotUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

var snapshotBeforeInsertHooks []SnapshotHook
var snapshotBeforeUpdateHooks []SnapshotHook
var snapshotBeforeDeleteHooks []SnapshotHook
var snapshotBeforeUpsertHooks []SnapshotHook

var snapshotAfterInsertHooks []SnapshotHook
var snapshotAfterSelectHooks []SnapshotHook
var snapshotAfterUpdateHooks []SnapshotHook
var snapshotAfterDeleteHooks []SnapshotHook
var snapshotAfterUpsertHooks []SnapshotHook

// doBeforeInsertHooks executes all "before insert" hooks.
func (o *Snapshot) doBeforeInsertHooks(exec boil.Executor) (err error) {
	for _, hook := range snapshotBeforeInsertHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpdateHooks executes all "before Update" hooks.
func (o *Snapshot) doBeforeUpdateHooks(exec boil.Executor) (err error) {
	for _, hook := range snapshotBeforeUpdateHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeDeleteHooks executes all "before Delete" hooks.
func (o *Snapshot) doBeforeDeleteHooks(exec boil.Executor) (err error) {
	for _, hook := range snapshotBeforeDeleteHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpsertHooks executes all "before Upsert" hooks.
func (o *Snapshot) doBeforeUpsertHooks(exec boil.Executor) (err error) {
	for _, hook := range snapshotBeforeUpsertHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterInsertHooks executes all "after Insert" hooks.
func (o *Snapshot) doAfterInsertHooks(exec boil.Executor) (err error) {
	for _, hook := range snapshotAfterInsertHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterSelectHooks executes all "after Select" hooks.
func (o *Snapshot) doAfterSelectHooks(exec boil.Executor) (err error) {
	for _, hook := range snapshotAfterSelectHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpdateHooks executes all "after Update" hooks.
func (o *Snapshot) doAfterUpdateHooks(exec boil.Executor) (err error) {
	for _, hook := range snapshotAfterUpdateHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterDeleteHooks executes all "after Delete" hooks.
func (o *Snapshot) doAfterDeleteHooks(exec boil.Executor) (err error) {
	for _, hook := range snapshotAfterDeleteHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpsertHooks executes all "after Upsert" hooks.
func (o *Snapshot) doAfterUpsertHooks(exec boil.Executor) (err error) {
	for _, hook := range snapshotAfterUpsertHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// AddSnapshotHook registers your hook function for all future operations.
func AddSnapshotHook(hookPoint boil.HookPoint, snapshotHook SnapshotHook) {
	switch hookPoint {
	case boil.BeforeInsertHook:
		snapshotBeforeInsertHooks = append(snapshotBeforeInsertHooks, snapshotHook)
	case boil.BeforeUpdateHook:
		snapshotBeforeUpdateHooks = append(snapshotBeforeUpdateHooks, snapshotHook)
	case boil.BeforeDeleteHook:
		snapshotBeforeDeleteHooks = append(snapshotBeforeDeleteHooks, snapshotHook)
	case boil.BeforeUpsertHook:
		snapshotBeforeUpsertHooks = append(snapshotBeforeUpsertHooks, snapshotHook)
	case boil.AfterInsertHook:
		snapshotAfterInsertHooks = append(snapshotAfterInsertHooks, snapshotHook)
	case boil.AfterSelectHook:
		snapshotAfterSelectHooks = append(snapshotAfterSelectHooks, snapshotHook)
	case boil.AfterUpdateHook:
		snapshotAfterUpdateHooks = append(snapshotAfterUpdateHooks, snapshotHook)
	case boil.AfterDeleteHook:
		snapshotAfterDeleteHooks = append(snapshotAfterDeleteHooks, snapshotHook)
	case boil.AfterUpsertHook:
		snapshotAfterUpsertHooks = append(snapshotAfterUpsertHooks, snapshotHook)
	}
}

// One returns a single snapshot record from the query.
func (q snapshotQuery) One(exec boil.Executor) (*Snapshot, error) {
	o := &Snapshot{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(nil, exec, o)
	if err != nil {
		if errors.Cause(err) == sql.ErrNoRows {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: failed to execute a one query for snapshots")
	}

	if err := o.doAfterSelectHooks(exec); err != nil {
		return o, err
	}

	return o, nil
}

// All returns all Snapshot records from the query.
func (q snapshotQuery) All(exec boil.Executor) (SnapshotSlice, error) {
	var o []*Snapshot

	err := q.Bind(nil, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "models: failed to assign all query results to Snapshot slice")
	}

	if len(snapshotAfterSelectHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterSelectHooks(exec); err != nil {
				return o, err
			}
		}
	}

	return o, nil
}

// Count returns the count of all Snapshot records in the query.
func (q snapshotQuery) Count(exec boil.Executor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRow(exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to count snapshots rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table.
func (q snapshotQuery) Exists(exec boil.Executor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRow(exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "models: failed to check if snapshots exists")
	}

	return count > 0, nil
}

// SnapRule pointed to by the foreign key.
func (o *Snapshot) SnapRule(mods ...qm.QueryMod) snapRuleQuery {
	queryMods := []qm.QueryMod{
		qm.Where("id=?", o.SnapRuleID),
	}

	queryMods = append(queryMods, mods...)

	query := SnapRules(queryMods...)
	queries.SetFrom(query.Query, "\"snap_rules\"")

	return query
}

// LoadSnapRule allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for an N-1 relationship.
func (snapshotL) LoadSnapRule(e boil.Executor, singular bool, maybeSnapshot interface{}, mods queries.Applicator) error {
	var slice []*Snapshot
	var object *Snapshot

	if singular {
		object = maybeSnapshot.(*Snapshot)
	} else {
		slice = *maybeSnapshot.(*[]*Snapshot)
	}

	args := make([]interface{}, 0, 1)
	if singular {
		if object.R == nil {
			object.R = &snapshotR{}
		}
		args = append(args, object.SnapRuleID)

	} else {
	Outer:
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &snapshotR{}
			}

			for _, a := range args {
				if a == obj.SnapRuleID {
					continue Outer
				}
			}

			args = append(args, obj.SnapRuleID)

		}
	}

	if len(args) == 0 {
		return nil
	}

	query := NewQuery(qm.From(`snap_rules`), qm.WhereIn(`id in ?`, args...))
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.Query(e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load SnapRule")
	}

	var resultSlice []*SnapRule
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice SnapRule")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for snap_rules")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for snap_rules")
	}

	if len(snapshotAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(e); err != nil {
				return err
			}
		}
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.SnapRule = foreign
		if foreign.R == nil {
			foreign.R = &snapRuleR{}
		}
		foreign.R.Snapshots = append(foreign.R.Snapshots, object)
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if local.SnapRuleID == foreign.ID {
				local.R.SnapRule = foreign
				if foreign.R == nil {
					foreign.R = &snapRuleR{}
				}
				foreign.R.Snapshots = append(foreign.R.Snapshots, local)
				break
			}
		}
	}

	return nil
}

// SetSnapRule of the snapshot to the related item.
// Sets o.R.SnapRule to related.
// Adds o to related.R.Snapshots.
func (o *Snapshot) SetSnapRule(exec boil.Executor, insert bool, related *SnapRule) error {
	var err error
	if insert {
		if err = related.Insert(exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE \"snapshots\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, []string{"snap_rule_id"}),
		strmangle.WhereClause("\"", "\"", 2, snapshotPrimaryKeyColumns),
	)
	values := []interface{}{related.ID, o.ID}

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, updateQuery)
		fmt.Fprintln(boil.DebugWriter, values)
	}

	if _, err = exec.Exec(updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	o.SnapRuleID = related.ID
	if o.R == nil {
		o.R = &snapshotR{
			SnapRule: related,
		}
	} else {
		o.R.SnapRule = related
	}

	if related.R == nil {
		related.R = &snapRuleR{
			Snapshots: SnapshotSlice{o},
		}
	} else {
		related.R.Snapshots = append(related.R.Snapshots, o)
	}

	return nil
}

// Snapshots retrieves all the records using an executor.
func Snapshots(mods ...qm.QueryMod) snapshotQuery {
	mods = append(mods, qm.From("\"snapshots\""))
	return snapshotQuery{NewQuery(mods...)}
}

// FindSnapshot retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindSnapshot(exec boil.Executor, iD int, selectCols ...string) (*Snapshot, error) {
	snapshotObj := &Snapshot{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from \"snapshots\" where \"id\"=$1", sel,
	)

	q := queries.Raw(query, iD)

	err := q.Bind(nil, exec, snapshotObj)
	if err != nil {
		if errors.Cause(err) == sql.ErrNoRows {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: unable to select from snapshots")
	}

	return snapshotObj, nil
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *Snapshot) Insert(exec boil.Executor, columns boil.Columns) error {
	if o == nil {
		return errors.New("models: no snapshots provided for insertion")
	}

	var err error
	currTime := time.Now().In(boil.GetLocation())

	if queries.MustTime(o.CreatedAt).IsZero() {
		queries.SetScanner(&o.CreatedAt, currTime)
	}
	if queries.MustTime(o.UpdatedAt).IsZero() {
		queries.SetScanner(&o.UpdatedAt, currTime)
	}

	if err := o.doBeforeInsertHooks(exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(snapshotColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	snapshotInsertCacheMut.RLock()
	cache, cached := snapshotInsertCache[key]
	snapshotInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			snapshotColumns,
			snapshotColumnsWithDefault,
			snapshotColumnsWithoutDefault,
			nzDefaults,
		)

		cache.valueMapping, err = queries.BindMapping(snapshotType, snapshotMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(snapshotType, snapshotMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO \"snapshots\" (\"%s\") %%sVALUES (%s)%%s", strings.Join(wl, "\",\""), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO \"snapshots\" %sDEFAULT VALUES%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			queryReturning = fmt.Sprintf(" RETURNING \"%s\"", strings.Join(returnColumns, "\",\""))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, cache.query)
		fmt.Fprintln(boil.DebugWriter, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRow(cache.query, vals...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	} else {
		_, err = exec.Exec(cache.query, vals...)
	}

	if err != nil {
		return errors.Wrap(err, "models: unable to insert into snapshots")
	}

	if !cached {
		snapshotInsertCacheMut.Lock()
		snapshotInsertCache[key] = cache
		snapshotInsertCacheMut.Unlock()
	}

	return o.doAfterInsertHooks(exec)
}

// Update uses an executor to update the Snapshot.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *Snapshot) Update(exec boil.Executor, columns boil.Columns) (int64, error) {
	currTime := time.Now().In(boil.GetLocation())

	queries.SetScanner(&o.UpdatedAt, currTime)

	var err error
	if err = o.doBeforeUpdateHooks(exec); err != nil {
		return 0, err
	}
	key := makeCacheKey(columns, nil)
	snapshotUpdateCacheMut.RLock()
	cache, cached := snapshotUpdateCache[key]
	snapshotUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			snapshotColumns,
			snapshotPrimaryKeyColumns,
		)

		if !columns.IsWhitelist() {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return 0, errors.New("models: unable to update snapshots, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE \"snapshots\" SET %s WHERE %s",
			strmangle.SetParamNames("\"", "\"", 1, wl),
			strmangle.WhereClause("\"", "\"", len(wl)+1, snapshotPrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(snapshotType, snapshotMapping, append(wl, snapshotPrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, cache.query)
		fmt.Fprintln(boil.DebugWriter, values)
	}

	var result sql.Result
	result, err = exec.Exec(cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update snapshots row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by update for snapshots")
	}

	if !cached {
		snapshotUpdateCacheMut.Lock()
		snapshotUpdateCache[key] = cache
		snapshotUpdateCacheMut.Unlock()
	}

	return rowsAff, o.doAfterUpdateHooks(exec)
}

// UpdateAll updates all rows with the specified column values.
func (q snapshotQuery) UpdateAll(exec boil.Executor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.Exec(exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all for snapshots")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected for snapshots")
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o SnapshotSlice) UpdateAll(exec boil.Executor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("models: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]interface{}, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), snapshotPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE \"snapshots\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), len(colNames)+1, snapshotPrimaryKeyColumns, len(o)))

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, sql)
		fmt.Fprintln(boil.DebugWriter, args...)
	}

	result, err := exec.Exec(sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all in snapshot slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected all in update all snapshot")
	}
	return rowsAff, nil
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *Snapshot) Upsert(exec boil.Executor, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns) error {
	if o == nil {
		return errors.New("models: no snapshots provided for upsert")
	}
	currTime := time.Now().In(boil.GetLocation())

	if queries.MustTime(o.CreatedAt).IsZero() {
		queries.SetScanner(&o.CreatedAt, currTime)
	}
	queries.SetScanner(&o.UpdatedAt, currTime)

	if err := o.doBeforeUpsertHooks(exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(snapshotColumnsWithDefault, o)

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	if updateOnConflict {
		buf.WriteByte('t')
	} else {
		buf.WriteByte('f')
	}
	buf.WriteByte('.')
	for _, c := range conflictColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	snapshotUpsertCacheMut.RLock()
	cache, cached := snapshotUpsertCache[key]
	snapshotUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, ret := insertColumns.InsertColumnSet(
			snapshotColumns,
			snapshotColumnsWithDefault,
			snapshotColumnsWithoutDefault,
			nzDefaults,
		)
		update := updateColumns.UpdateColumnSet(
			snapshotColumns,
			snapshotPrimaryKeyColumns,
		)

		if updateOnConflict && len(update) == 0 {
			return errors.New("models: unable to upsert snapshots, could not build update column list")
		}

		conflict := conflictColumns
		if len(conflict) == 0 {
			conflict = make([]string, len(snapshotPrimaryKeyColumns))
			copy(conflict, snapshotPrimaryKeyColumns)
		}
		cache.query = buildUpsertQueryPostgres(dialect, "\"snapshots\"", updateOnConflict, ret, update, conflict, insert)

		cache.valueMapping, err = queries.BindMapping(snapshotType, snapshotMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(snapshotType, snapshotMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []interface{}
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, cache.query)
		fmt.Fprintln(boil.DebugWriter, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRow(cache.query, vals...).Scan(returns...)
		if err == sql.ErrNoRows {
			err = nil // Postgres doesn't return anything when there's no update
		}
	} else {
		_, err = exec.Exec(cache.query, vals...)
	}
	if err != nil {
		return errors.Wrap(err, "models: unable to upsert snapshots")
	}

	if !cached {
		snapshotUpsertCacheMut.Lock()
		snapshotUpsertCache[key] = cache
		snapshotUpsertCacheMut.Unlock()
	}

	return o.doAfterUpsertHooks(exec)
}

// Delete deletes a single Snapshot record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *Snapshot) Delete(exec boil.Executor) (int64, error) {
	if o == nil {
		return 0, errors.New("models: no Snapshot provided for delete")
	}

	if err := o.doBeforeDeleteHooks(exec); err != nil {
		return 0, err
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), snapshotPrimaryKeyMapping)
	sql := "DELETE FROM \"snapshots\" WHERE \"id\"=$1"

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, sql)
		fmt.Fprintln(boil.DebugWriter, args...)
	}

	result, err := exec.Exec(sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete from snapshots")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by delete for snapshots")
	}

	if err := o.doAfterDeleteHooks(exec); err != nil {
		return 0, err
	}

	return rowsAff, nil
}

// DeleteAll deletes all matching rows.
func (q snapshotQuery) DeleteAll(exec boil.Executor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("models: no snapshotQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.Exec(exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from snapshots")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for snapshots")
	}

	return rowsAff, nil
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o SnapshotSlice) DeleteAll(exec boil.Executor) (int64, error) {
	if o == nil {
		return 0, errors.New("models: no Snapshot slice provided for delete all")
	}

	if len(o) == 0 {
		return 0, nil
	}

	if len(snapshotBeforeDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doBeforeDeleteHooks(exec); err != nil {
				return 0, err
			}
		}
	}

	var args []interface{}
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), snapshotPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM \"snapshots\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, snapshotPrimaryKeyColumns, len(o))

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, sql)
		fmt.Fprintln(boil.DebugWriter, args)
	}

	result, err := exec.Exec(sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from snapshot slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for snapshots")
	}

	if len(snapshotAfterDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterDeleteHooks(exec); err != nil {
				return 0, err
			}
		}
	}

	return rowsAff, nil
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *Snapshot) Reload(exec boil.Executor) error {
	ret, err := FindSnapshot(exec, o.ID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *SnapshotSlice) ReloadAll(exec boil.Executor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := SnapshotSlice{}
	var args []interface{}
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), snapshotPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT \"snapshots\".* FROM \"snapshots\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, snapshotPrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(nil, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "models: unable to reload all in SnapshotSlice")
	}

	*o = slice

	return nil
}

// SnapshotExists checks if the Snapshot row exists.
func SnapshotExists(exec boil.Executor, iD int) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from \"snapshots\" where \"id\"=$1 limit 1)"

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, sql)
		fmt.Fprintln(boil.DebugWriter, iD)
	}

	row := exec.QueryRow(sql, iD)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "models: unable to check if snapshots exists")
	}

	return exists, nil
}
